Implement basic sky (sun & moon) + fix matrices
wgpu-mc/wgpu-mc pull request #102
Opened 2024-01-02 18:01 UTC by Zanctarian

originally was just implementing a basic sky, but while working on the sun, I figured out how to get matrices better translated. World effects like bobbing and nausea work now.

2024-01-02 19:20 UTC, birbe requested changes

2024-01-02 19:20 UTC, birbe commented on rust/wgpu-mc/src/mc/mod.rs
> +#[derive(Default)]
why not just use `#[derive(Clone)]`?

2024-01-02 19:20 UTC, birbe commented on rust/wgpu-mc-jni/src/renderer.rs
> +    if id == 0 {
use a match brace

2024-01-02 19:21 UTC, Zanctarian commented on rust/wgpu-mc/src/mc/mod.rs
> +#[derive(Default)]
wont let me because of the hashmap

2024-01-04 09:51 UTC, Zanctarian commented on rust/wgpu-mc-jni/src/renderer.rs
> +    if id == 0 {
👍

2024-01-04 10:00 UTC, Zanctarian commented
note: vecs don't seem to work with push constants.  They get inverted and the shaders don't read the right spot in memory. Hopefully the graph rework on the next wgpu major version will allow vec push constants. As a temporary workaround, I just passed each axis as a f32.

other than that, tested and ready to merge after review

2024-01-04 14:33 UTC, merged